### ISSUE TITLE
HMI_Simulation_Ubuntu1604_15_x86_64.x86_64 is no such file

### ISSUE THREAD

**Issue by harry1080** [djformby/GRFICS#6]
sudo ./HMI_Simulation_Ubuntu1604_15_x86_64.x86_64
![image](https://user-images.githubusercontent.com/19358692/103628408-ebc31580-4f79-11eb-8112-0f9a9aad7080.png)

**Comment by djformby** [comment]
I'm sorry that the naming is confusing, but it looks like the command you ran was ./HMI_Simulation_Ubuntu1604_15_x86_64 instead of ./HMI_Simulation_Ubuntu1604_15_x86_64**.x86_64** Please try again making sure to add the .x86_64 on the end

**Comment by harry1080** [comment]
> I'm sorry that the naming is confusing, but it looks like the command you ran was ./HMI_Simulation_Ubuntu1604_15_x86_64 instead of ./HMI_Simulation_Ubuntu1604_15_x86_64**.x86_64** Please try again making sure to add the .x86_64 on the end

ok，Resolved, thanks
