### ISSUE TITLE
On the problem of Simulation environment startup

### ISSUE THREAD

**Issue by harry1080** [djformby/GRFICS#7]
Question 1:

Hello, I finished sudo. / HMI when I finished the fifth step_ Simulation_ Ubuntu1604_ 15_ x86_ 64.x86_ 64, there is no need to enter the path (/ home / user / simulation / simulation), directly pop up to select the display resolution, select to complete the resolution, pop up a TCP black window, how to deal with

![image](https://user-images.githubusercontent.com/19358692/103720945-7a31a880-5007-11eb-8240-fe9704fd598e.png)
![image](https://user-images.githubusercontent.com/19358692/103720958-83227a00-5007-11eb-8ecf-42459f5a8ec4.png)
![image](https://user-images.githubusercontent.com/19358692/103720979-8f0e3c00-5007-11eb-8fe5-53df02ab15cc.png)

Question 2:

The default configuration of my network card is 192.95

HDM default dual network card ens33 configuration 192.168.95.3

The default configuration of ens33 is 192.168.95.4

Is there any problem with this configuration? Do you need it

**Comment by kepjr2** [comment]
@harry1080 did you ever get an answer or fix for your Question 2? I am experiencing the same

**Comment by harry1080** [comment]
> @harry1080 did you ever get an answer or fix for your Question 2? I am experiencing the same

I still haven't solved it

**Comment by utchy-su** [comment]
@harry1080 Hi harry1080
Have you solved this issue? I'm experiencing the same problem and haven't found any good practices to avoid it. I would appreciate if you share the workaround. Thanks.

**Comment by utchy-su** [comment]
seems I figured it out.

It needed to strictly follow this instruction (which i forgot to)

Log into the simulation VM and open 2 terminals. In one, cd into the "HMI_Simulation_Ubuntu1604_15_x86_64" directory and run "sudo ./HMI_Simulation_Ubuntu1604_15_x86_64.x86_64". **Enter "/home/user/simulation/simulation" for the path to the simulation code, click "Run Server" and then click "Start". In the second terminal, cd into the simulation/remote_io directory and run "sudo bash run_all.sh"**
